### ISSUE TITLE
[BUG] 1.7.10 projects not load (no error)

### ISSUE THREAD

**Issue by TheDWPCer** [CJMinecraft01/ForgeModBuilder#16]
I don't know if this is on purpose, but 1.7.10 projects fail to load

I have tried loading the entire project, and just the eclipse folder in the project.

I understand that 1.7.10 is a dead version but...  I want to be able to update the version in some way.

the error just says unable to load project (project not found)

**Comment by CJMinecraft01** [comment]
Do you have a build.gradle file and gradlew.bat file? If not, then the project would show this error

**Comment by TheDWPCer** [comment]
![image](https://user-images.githubusercontent.com/15698234/41562271-bc1fcc70-7311-11e8-9ca4-b1e0de06d5e0.png)


good idea, but there it is

**Comment by CJMinecraft01** [comment]
Are you putting it in the mod folder or the .eclipse folder?

**Comment by TheDWPCer** [comment]
I have tried both

**Comment by CJMinecraft01** [comment]
I'll take a look more tomorrow, and I'll see if I can figure this out

**Comment by TheDWPCer** [comment]
I don't know if this will help but here is the environment: https://www.dropbox.com/s/afspag42eixa25x/checkdev-OPEN%20inside%20of%20a%20folder%20DONT%20Open%20on%20desktop.zip?dl=1

open it in a new folder, or the stuff will go everywhere

**Comment by CJMinecraft01** [comment]
Sorry for the long wait. I've been working on the rewrite of the project. I have found the part which was causing the issue. Unfortunately for me, it is with the code. In the build.gradle file, FMB accesses the minecraft version of the project by reading the value of the variable "version". In 1.8 onwards the variable will read "MCVERSION-FORGEVERSION" (e.g. "1.11.2-13.20.1.2579") but for versions below, it seems to be different.  The line in the 1.7.10 version reads "1.7.10-10.13.4.1558-1.7.10" which means FMB gets a bit confused. Also, it appears as though mappings are not needed in 1.7.10 and below in the build file, which FMB depends on whilst updating. This is because, it uses an old version of ForgeGradle which apparently does not need mappings. Annoyingly this is not integrated into FMB as I was not aware of this at the time. I do plan on fixing this, but it is more probable that it will happen in the rewrite which should be coming out this month (hopefully)

**Comment by TheDWPCer** [comment]
Fixed in 0.1.1.3.  Thanks CJ.
